version: "3.7"
services:
  app:
    build:
      context: .
    container_name: maint-app
    volumes:
      - ./content:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:maint.mythcoders.dev'

networks:
  default:
    name: mythcoders_dev
    external: true
